name: Merge `autoupdate` branches

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Automatically merge branches labeled as `autoupdate`
        uses: "pascalgn/automerge-action@v0.14.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "autoupdate"
          MERGE_METHOD: "rebase"
          UPDATE_METHOD: "rebase"
          UPDATE_RETRIES : 10
          UPDATE_RETRY_SLEEP: 30