name: build and test

on:
  push:
  pull_request:

env:
  DOTNET_VERSION: '6.0'

jobs:
  build-and-test:

    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test and collect code coverage
      run: dotnet test UnityVersionBump.Core.Tests/UnityVersionBump.Core.Tests.csproj \
             --no-build \
             --verbosity normal \
             --results-directory "${{ github.workspace }}/TestResults" \
             /p:CollectCoverage=true \
             /p:CoverletOutputFormat=opencover

    - name: Upload test coverage
      uses: codecov/codecov-action@v1
      with:
        flags: ${{ matrix.framework }}